# Generated by Django 2.1.4 on 2019-01-15 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customer_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ln1', models.CharField(default='', max_length=30)),
                ('ln2', models.CharField(default='', max_length=15)),
                ('city', models.CharField(default='Seattle', max_length=20)),
                ('state', models.CharField(default='WA', max_length=2)),
                ('postal_code', models.CharField(default='98105', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Customers.Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.CharField(choices=[('AA', 'Apple Appointment'), ('AR', 'Apple Recommendation'), ('IS', 'Internet Search')], max_length=2),
        ),
    ]
